### PR TITLE
Make code Python 2 and 3 compatible

### PR DESCRIPTION
**Pull request by jrings**
Ok, this passes all the tests in Python 2 and 3. It probably will make the code not work in old Python2, 2.4 or older, since `xrange` and `iteritems` have been replaced with modern versions, but since 2.4 is so old that should be fine.

### CODE REVIEW

**Comment by jrings** [comment]
Ok, I have started again with Python 3 compatibility, and gotten a good bunch of the tests fixed. But I'm stuck on things using the EPAnet simulator. Whenever I run anything that uses it, e.g. examples/getting_started.py", it errors out with the error code for file not found. I tracked it, and notmp.rst` is created when I run code in Python 3 (works in 2). Since this is hidden in Cython or C code, I think, I wonder if you have an idea of why this could happen or how to start debugging it?

**Comment by michaelbynum** [comment]
Joerg,

Can you help me reproduce your error? I cloned your fork of the repository.
When I use python3, I get an import error (No module named 'pyepanet').
This does not sound like the same error you are getting. Which branch of
your fork are you on?

Thanks,
Michael

**Comment by jrings** [comment]
Hmm, interesting, I just installed a fresh anaconda environment to document the steps:

```bash
source deactivate  # Only if you're in an env
conda create -n pytest3 python=3 scipy nose networkx numpy pandas matplotlib sympy
cd
git clone https://github.com/jrings/WNTR.git
cd WNTR
git checkout compat_2and3
python setup.py develop
nosetests
```

This should lead to the 302 errors

**Comment by kaklise** [comment]
The error is caused by differences in the way python 2 and 3 handle strings.  Updated code, which incorporates the compat_2and3 branch, will be submitted as a separate pull request.

**Comment by kaklise** [comment]
Closed by #16

**Pull request closed without merging**
