### PR TITLE
Toolkit update

### PR DESCRIPTION
**Pull request by dbhart**
Update to provide thread-safe EPANET 2.2 simulator and to add a few get/set functions missing from the toolkit.py module.

### CODE REVIEW

**Comment by dbhart** [comment]
Full list of changes:

- Added ENgetnodevalue, ENsetnodevalue, ENgetlinkvalue, ENsetlinkvalue, ENgettimeparam, and ENsettimeparam functions to the ENepanet toolkit class.
- Added testing and API documentation for all the preceding functions
- Added thread testing for both EpanetSimulator and WNTRSimulator
- Change ENepanet to use thread-safe functions internally for all version 2.2 functions

**Review by kaklise — COMMENTED** [review]
This looks good to me.  Can you add a short entry to the user manual that describes the capability using the EpanetSimulator and WNTRSimulator?  We could start an "Advanced Simulation Capabilities" section or add a subsection in "Hydraulic Simulation".

**Comment by dbhart** [comment]
@kaklise I think it might be good to start an advanced simulation capabilities section. Would that be a new file in the documentation directory?

**Comment by kaklise** [comment]
Yes. We could also move the "Customized models with WNTR’s AML" into that section.  Let's draft this offline.

**Comment by dbhart** [comment]
@kaklise I think this is ready for a code review.

**Pull request merged**
